spring:
  data:
    mongodb:
      uri: mongodb://localhost/test

server:
  port: 9001
  
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/